set(_CATKIN_CURRENT_PACKAGE "mavric")
set(mavric_VERSION "0.0.0")
set(mavric_MAINTAINER "pi <pi@todo.todo>")
set(mavric_PACKAGE_FORMAT "1")
set(mavric_BUILD_DEPENDS "rospy" "std_msgs")
set(mavric_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(mavric_BUILDTOOL_DEPENDS "catkin")
set(mavric_BUILDTOOL_EXPORT_DEPENDS )
set(mavric_EXEC_DEPENDS "rospy" "std_msgs")
set(mavric_RUN_DEPENDS "rospy" "std_msgs")
set(mavric_TEST_DEPENDS )
set(mavric_DOC_DEPENDS )
set(mavric_DEPRECATED "")